name: NPM Publish on Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    # Publish to npm
    - run: git config --global user.name "Gazin"
    - run: git config --global user.email "gazin@gazin.com.br"
    - run: yarn publish --new-version ${{ github.event.release.tag_name }} --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@tigdevs'
    # Publish to GitHub Packages
    - run: yarn publish --new-version ${{ github.event.release.tag_name }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
